<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8cbBXl6\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8cbBXl6/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container8cbBXl6.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container8cbBXl6\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container8cbBXl6\App_KernelProdContainer([
    'container.build_hash' => '8cbBXl6',
    'container.build_id' => '62a3bed8',
    'container.build_time' => 1598273969,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8cbBXl6');
