<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDMvaj5q\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDMvaj5q/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDMvaj5q.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDMvaj5q\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDMvaj5q\App_KernelDevDebugContainer([
    'container.build_hash' => 'DMvaj5q',
    'container.build_id' => '8fdc7c58',
    'container.build_time' => 1598273962,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDMvaj5q');
