<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Sortie extends \App\Entity\Sortie implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Sortie' . "\0" . 'SortieId', '' . "\0" . 'App\\Entity\\Sortie' . "\0" . 'nomSortie', '' . "\0" . 'App\\Entity\\Sortie' . "\0" . 'etat', '' . "\0" . 'App\\Entity\\Sortie' . "\0" . 'dateHeure', '' . "\0" . 'App\\Entity\\Sortie' . "\0" . 'dateLimiteInscription', '' . "\0" . 'App\\Entity\\Sortie' . "\0" . 'inscrie', '' . "\0" . 'App\\Entity\\Sortie' . "\0" . 'nbplaces', '' . "\0" . 'App\\Entity\\Sortie' . "\0" . 'duree', '' . "\0" . 'App\\Entity\\Sortie' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Sortie' . "\0" . 'ville', '' . "\0" . 'App\\Entity\\Sortie' . "\0" . 'campus', '' . "\0" . 'App\\Entity\\Sortie' . "\0" . 'rue', '' . "\0" . 'App\\Entity\\Sortie' . "\0" . 'codePostal', '' . "\0" . 'App\\Entity\\Sortie' . "\0" . 'organisateur', '' . "\0" . 'App\\Entity\\Sortie' . "\0" . 'motifAnnulation', 'container'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Sortie' . "\0" . 'SortieId', '' . "\0" . 'App\\Entity\\Sortie' . "\0" . 'nomSortie', '' . "\0" . 'App\\Entity\\Sortie' . "\0" . 'etat', '' . "\0" . 'App\\Entity\\Sortie' . "\0" . 'dateHeure', '' . "\0" . 'App\\Entity\\Sortie' . "\0" . 'dateLimiteInscription', '' . "\0" . 'App\\Entity\\Sortie' . "\0" . 'inscrie', '' . "\0" . 'App\\Entity\\Sortie' . "\0" . 'nbplaces', '' . "\0" . 'App\\Entity\\Sortie' . "\0" . 'duree', '' . "\0" . 'App\\Entity\\Sortie' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Sortie' . "\0" . 'ville', '' . "\0" . 'App\\Entity\\Sortie' . "\0" . 'campus', '' . "\0" . 'App\\Entity\\Sortie' . "\0" . 'rue', '' . "\0" . 'App\\Entity\\Sortie' . "\0" . 'codePostal', '' . "\0" . 'App\\Entity\\Sortie' . "\0" . 'organisateur', '' . "\0" . 'App\\Entity\\Sortie' . "\0" . 'motifAnnulation', 'container'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Sortie $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getSortieId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSortieId', []);

        return parent::getSortieId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSortieId($SortieId): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSortieId', [$SortieId]);

        parent::setSortieId($SortieId);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomSortie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomSortie', []);

        return parent::getNomSortie();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomSortie($nomSortie): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomSortie', [$nomSortie]);

        parent::setNomSortie($nomSortie);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateHeure()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateHeure', []);

        return parent::getDateHeure();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateHeure($dateHeure): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateHeure', [$dateHeure]);

        parent::setDateHeure($dateHeure);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateLimiteInscription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateLimiteInscription', []);

        return parent::getDateLimiteInscription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateLimiteInscription($dateLimiteInscription): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateLimiteInscription', [$dateLimiteInscription]);

        parent::setDateLimiteInscription($dateLimiteInscription);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbplaces()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbplaces', []);

        return parent::getNbplaces();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbplaces($nbplaces): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbplaces', [$nbplaces]);

        parent::setNbplaces($nbplaces);
    }

    /**
     * {@inheritDoc}
     */
    public function getDuree()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDuree', []);

        return parent::getDuree();
    }

    /**
     * {@inheritDoc}
     */
    public function setDuree($duree): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDuree', [$duree]);

        parent::setDuree($duree);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', []);

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille($ville): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', [$ville]);

        parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getRue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRue', []);

        return parent::getRue();
    }

    /**
     * {@inheritDoc}
     */
    public function setRue($rue): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRue', [$rue]);

        parent::setRue($rue);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodePostal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodePostal', []);

        return parent::getCodePostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodePostal($codePostal): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodePostal', [$codePostal]);

        parent::setCodePostal($codePostal);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', []);

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat($etat): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganisateur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganisateur', []);

        return parent::getOrganisateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrganisateur(\App\Entity\Utilisateur $organisateur): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrganisateur', [$organisateur]);

        parent::setOrganisateur($organisateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getInscrie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInscrie', []);

        return parent::getInscrie();
    }

    /**
     * {@inheritDoc}
     */
    public function setInscrie($inscrie): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInscrie', [$inscrie]);

        parent::setInscrie($inscrie);
    }

    /**
     * {@inheritDoc}
     */
    public function getCampus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCampus', []);

        return parent::getCampus();
    }

    /**
     * {@inheritDoc}
     */
    public function setCampus($campus): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCampus', [$campus]);

        parent::setCampus($campus);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotifAnnulation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotifAnnulation', []);

        return parent::getMotifAnnulation();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotifAnnulation($motifAnnulation): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotifAnnulation', [$motifAnnulation]);

        parent::setMotifAnnulation($motifAnnulation);
    }

    /**
     * {@inheritDoc}
     */
    public function setContainer(\Psr\Container\ContainerInterface $container): ?\Psr\Container\ContainerInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContainer', [$container]);

        return parent::setContainer($container);
    }

}
